[package]
name = "firesim"
version = "0.1.0"
authors = ["karim <karim.elmougi@gmail.com>"]
edition = "2018"

[dependencies]
num-format = "0.4.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

