inflation = 1.02 
salary_growth = 1.1
return_on_investment = 1.07

# How much to withdraw from the portfolio each year during retirement
# Higher rate -> less time to save up for retirement but higher chance of 
# prematurely exhausting funds
# Lower rate -> more time to save up for retirement but less chance of 
# prematurely exhausting funds
# In particular, this value should be kept inferior to your ROI minus inflation
# if long-term sustainability is desired
# 4% is safe in more than 90% of historical 40 year periods
# 3% is rock-solid in all historical 40 year periods
withdraw_rate = 0.04

salary = 140_000
salary_cap = 500_000
cost_of_living = 25_000
retirement_cost_of_living = 25_000

employer_rrsp_match = 0.06
rrsp_contribution_headroom = 14_400
rrsp_assets = 15_000
tfsa_assets = 24_000
unregistered_assets = 0

# Quebec
[[provincial_tax_brackets]]
  lower_bound = 0
  upper_bound = 15728
  rate = 0.0
[[provincial_tax_brackets]]
  lower_bound = 15728
  upper_bound = 45105
  rate = 15.0
[[provincial_tax_brackets]]
  lower_bound = 45105
  upper_bound = 90200
  rate = 20.0
[[provincial_tax_brackets]]
  lower_bound = 90200
  upper_bound = 109755
  rate = 24.0
[[provincial_tax_brackets]]
  lower_bound = 109755
  upper_bound = 999999
  rate = 25.75

# Ontario
#[[provincial_tax_brackets]]
  #lower_bound = 0
  #upper_bound = 10880
  #rate = 0.0
#[[provincial_tax_brackets]]
  #lower_bound = 10880
  #upper_bound = 45142
  #rate = 5.05
#[[provincial_tax_brackets]]
  #lower_bound = 45142
  #upper_bound = 90287
  #rate = 9.15
#[[provincial_tax_brackets]]
  #lower_bound = 90287
  #upper_bound = 150000
  #rate = 11.16
#[[provincial_tax_brackets]]
  #lower_bound = 150000
  #upper_bound = 220000
  #rate = 12.16
#[[provincial_tax_brackets]]
  #lower_bound = 220000
  #upper_bound = 999999
  #rate = 13.16

# Canada
[[federal_tax_brackets]]
  lower_bound = 0
  upper_bound = 13808
  rate = 0.0
[[federal_tax_brackets]]
  lower_bound = 13808
  upper_bound = 49020
  rate = 15.0
[[federal_tax_brackets]]
  lower_bound = 49020
  upper_bound = 98040
  rate = 20.5
[[federal_tax_brackets]]
  lower_bound = 98040
  upper_bound = 151978
  rate = 26.0
[[federal_tax_brackets]]
  lower_bound = 151978
  upper_bound = 216511
  rate = 29.75
[[federal_tax_brackets]]
  lower_bound = 216511
  upper_bound = 999999
  rate = 33.0

# Washington State
#  [[provincial_tax_brackets]]
#  lower_bound = 0
#  upper_bound = 999_999
#  rate = 2.75

# USA
#[[federal_tax_brackets]]
  #lower_bound = 0
  #upper_bound = 9875
  #rate = 10
#[[federal_tax_brackets]]
  #lower_bound = 9875
  #upper_bound = 40125
  #rate = 12
#[[federal_tax_brackets]]
  #lower_bound = 40125
  #upper_bound = 85525
  #rate = 22
#[[federal_tax_brackets]]
  #lower_bound = 85525
  #upper_bound = 163300
  #rate = 24
#[[federal_tax_brackets]]
  #lower_bound = 163300
  #upper_bound = 207350
  #rate = 32
#[[federal_tax_brackets]]
  #lower_bound = 207350
  #upper_bound = 518400
  #rate = 35
#[[federal_tax_brackets]]
  #lower_bound = 518400
  #upper_bound = 999_999
  #rate = 37

