inflation = 1.02
salary_growth = 1.08
return_on_investment = 1.07
goal_multiplier = 30

salary = 75000
cost_of_living = 25000
retirement_cost_of_living = 25000

rrsp_contribution_headroom = 10000
rrsp_assets = 0
tfsa_assets = 0
unregistered_assets = 0

# Quebec
[[provincial_tax_brackets]]
  lower_bound = 0
  upper_bound = 15728
  percentage = 0.0
[[provincial_tax_brackets]]
  lower_bound = 15728
  upper_bound = 45105
  percentage = 15.0
[[provincial_tax_brackets]]
  lower_bound = 45105
  upper_bound = 90200
  percentage = 20.0
[[provincial_tax_brackets]]
  lower_bound = 90200
  upper_bound = 109755
  percentage = 24.0
[[provincial_tax_brackets]]
  lower_bound = 109755
  upper_bound = 999999
  percentage = 25.75

# Ontario
#[[provincial_tax_brackets]]
  #lower_bound = 0
  #upper_bound = 10880
  #percentage = 0.0
#[[provincial_tax_brackets]]
  #lower_bound = 10880
  #upper_bound = 45142
  #percentage = 5.05
#[[provincial_tax_brackets]]
  #lower_bound = 45142
  #upper_bound = 90287
  #percentage = 9.15
#[[provincial_tax_brackets]]
  #lower_bound = 90287
  #upper_bound = 150000
  #percentage = 11.16
#[[provincial_tax_brackets]]
  #lower_bound = 150000
  #upper_bound = 220000
  #percentage = 12.16
#[[provincial_tax_brackets]]
  #lower_bound = 220000
  #upper_bound = 999999
  #percentage = 13.16

# Canada
[[federal_tax_brackets]]
  lower_bound = 0
  upper_bound = 13808
  percentage = 0.0
[[federal_tax_brackets]]
  lower_bound = 13808
  upper_bound = 49020
  percentage = 15.0
[[federal_tax_brackets]]
  lower_bound = 49020
  upper_bound = 98040
  percentage = 20.5
[[federal_tax_brackets]]
  lower_bound = 98040
  upper_bound = 151978
  percentage = 26.0
[[federal_tax_brackets]]
  lower_bound = 151978
  upper_bound = 216511
  percentage = 29.75
[[federal_tax_brackets]]
  lower_bound = 216511
  upper_bound = 999999
  percentage = 33.0

